### ISSUE TITLE
Error. Cannot make tmpdir. Exit

### ISSUE THREAD

**Issue by Yewhoo** [CaronLab/MhcVizPipe#8]
I tried to search my file and I got this msg at the end of my terminal. After awhile, i get the following msg in my browser GUI:

Traceback (most recent call last):
  File "/mnt/c/Users/lym16/MhcVizPipe/python/lib/python3.8/site-packages/MhcVizPipe/gui.py", line 1083, in run_analysis
    _ = analysis.make_report()
  File "/mnt/c/Users/lym16/MhcVizPipe/python/lib/python3.8/site-packages/MhcVizPipe/ReportTemplates/report.py", line 766, in make_report
    self.sample_overview_table(className='col-6')
  File "/mnt/c/Users/lym16/MhcVizPipe/python/lib/python3.8/site-packages/MhcVizPipe/ReportTemplates/report.py", line 153, in sample_overview_table
    within_length = self.peptide_numbers[sample.sample_name]['total']
KeyError: 'de_novo_only_peptides.csv'

I can't seem to fix it.

**Comment by kevinkovalchik** [comment]
Hello,

Thanks for your interest in the tool, and I'm sorry that it is not running properly for you. The error in your issue title looks like a NetMHCpan error that happens when it can't make a temporary directory. Are you using the standalone version of MhcVizPipe or did you install it through pip?

**If using the standalone version:**

By default we are using the /tmp directory for NetMHCpan's tempdir location. Do you know if you have write permissions in the /tmp directory? This should almost always be the case, but if you don't that would explain the problem. If that is the problem I can help you set up NetMHCpan and NetMHCIIpan to use a different location for the temp files, and I can make a tmpdir location in the settings in the next release so it can be changed through the GUI.

**If you installed through pip:**
In this case it might be that the TMPDIR variable in your NetMHCpan or NetMHCIIpan files is not set correctly, so the program is not able to make the directory. Or another possibility is that the path is set correctly, but the folder doesn't exist. The tools won't make the temp directory for you, so make sure that whatever TMPDIR is set to exists already.

In either case, the the error you got in the GUI is obviously not very helpful, so I will try to address this in the next release as well.

Best wishes,
Kevin

**Comment by kevinkovalchik** [comment]
Hello again. Were you able to resolve this issue?

Thanks,
Kevin

**Comment by Yewhoo** [comment]
Hi Kevin,

Sorry for the late reply! I manually edited all the script settings and it
finally worked out. Thanks for some useful pointers!

Warmest regards,
Yew Mun

**Comment by kevinkovalchik** [comment]
Hi Yew Mun,

That's good to hear! Which script files did you need to edit? Was it a problem with the MhcVizPipe distribution? Or did you use seperate installations of netMHCpan and GibbsCluster that needed to be set up? I'm just trying to determine if I need to fix anything in the "standalone" distribution of MhcVizPipe.

Thanks!
Kevin

**Comment by Yewhoo** [comment]
Hi Kevin,

After reading your suggestions, I went to read more in details of the
installation of gibbscluster, NetMHCI and NetMHCII installation. Initially
if I were to do the easy installation approach, there were no
instructions that requires for checking the general settings of these tools
to the exact directory where it is stored (i.e., the tools folder of
MhcVizPipe). So after reading the manual installation of how to do it, and
changing the location and tmp folder location (i tried to give root/admin
access to the tmp folder but nothing happened) to my desired location, i
was able to get the programme to run. Therefore, the standalone
distribution is okay, just need to tweak the instruction. :)

Thanks and warmest regards,
Yew Mun

**Comment by kevinkovalchik** [comment]
Hi Yew Mun,

Thanks for your feedback! There are supposed to be some scripts in the standalone installation that are already set up to run the tools in the"tools" folder, but I'll have to go have a look at them! Sometimes I think things work on my test systems, but it is only because I have run them so many times that I forget to reset everything before testing... :)

I'll go ahead and close this issue. Let me know if any other problems come up.

Best wishes,
Kevin
